happy_shop/urls.py
from rest_framework.documentation import include_docs_urls
from django.urls import path, include
from .import views

app_name = "happy_shop"

urlpatterns = [
    path('api/', include('happy_shop.api.api_urls')),
    path('docs/', include_docs_urls(title='HappyShop API')),
    path('api-auth/', include('rest_framework.urls')),
    
    # PC端
    path("", views.IndexView.as_view(), name="index"),
    path("all_category/", views.HappyShopCategoryAllView.as_view(), name="all_category"),
    path("goods/<int:pk>/", views.HappyShopCategoryView.as_view(), name="goods"),
    path("goods/<int:pk>/detail/", views.HappyShopSPUDetailView.as_view(), name="goods_detail"),
    path("cart/", views.HappyShopingCartView.as_view(), name="cart"),
    path("pay/", views.HappyShopPayView.as_view(), name="pay"),
    path('user_profile/', views.HappyShopUserProfileView.as_view(), name='user_profile'),
    path('user_orders/', views.HappyShopUserOrdersView.as_view(), name='user_orders'),
    path('user_orders/<int:pk>/', views.HappyShopUserOrdersDetailView.as_view(), name='user_orders_detail'),
    path('user_address/', views.HappyShopUserAddressView.as_view(), name='user_address'),
    path("user_orders_sku/<int:pk>/", views.HappyShopOrderSKUDetailView.as_view(), name="user_orders_sku_detail"),
    
    
    path("login/", views.HappyShopLoginView.as_view(), name="login"),
    path("register/", views.HappyShopRegisterView.as_view(), name="register"),
    path('logout/', views.HappyShopLogoutView.as_view(), name='logout'),
    path('upload_img/', views.HappyShopUploadImage.as_view(), name="upload_img"),
]


# 支付宝支付的回调URL
from rest_framework.urlpatterns import format_suffix_patterns
from happy_shop.api.views import AliPayView

api_urlpatterns = [
    path('api/alipay/', AliPayView.as_view(), name="alipay"),
]

urlpatterns += format_suffix_patterns(api_urlpatterns)

happy_shop/models/order.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from .models import BaseModelMixin
from .goods import HappyShopSKU

User = get_user_model()


class HappyShopOrderInfo(BaseModelMixin):
    """订单信息"""

    class PayMethodChoices(models.IntegerChoices):
        CASH = 1, _('货到付款')
        ALIPAY = 2, _('支付宝')
        WECHATPAY = 3, _('微信支付')
        OVERPAY = 4, _('余额支付')

    class OrderStatusChoices(models.IntegerChoices):
        TOBPAY = 1, _('待支付')
        TOBDELIVER = 2, _('待发货')
        TOBRECEIVED = 3, _('待收货')
        TOBEVALUATE = 4, _('待评价')
        COMPLETE = 5, _('已完成')
        CANCELLED = 6, _('已取消')

    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="用户")
    order_sn = models.CharField(
        blank=True, default="",
        unique=True, max_length=32,
        verbose_name="订单号", help_text="订单号")
    trade_sn = models.CharField(
        blank=True, null=True,
        unique=True, max_length=64,
        verbose_name="交易号", help_text="交易号")
    pay_status = models.IntegerField(
        choices=OrderStatusChoices.choices, default=1, verbose_name="支付状态", help_text="支付状态")
    pay_method = models.IntegerField(
        choices=PayMethodChoices.choices, default=2, verbose_name="支付方式", help_text="支付方式")
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name="商品总金额")
    order_mark = models.CharField(
        blank=True, default="", max_length=100, verbose_name="订单备注", help_text="订单备注")
    freight = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name="运费")
    name = models.CharField("签收人", max_length=50, default="")
    phone = models.CharField("手机号", max_length=11, default="")
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    address = models.CharField("地址", max_length=150)
    pay_time = models.DateTimeField(
        null=True, blank=True, verbose_name="支付时间", help_text="支付时间")

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn

    @classmethod
    def get_pay_method(cls):
        # 支付方式列表字典
        return dict(cls.PayMethodChoices.choices)

    @classmethod
    def get_pay_default(cls):
        # 获取支付方式的默认值
        return cls._meta.get_field('pay_method').default


class HappyShopOrderSKU(BaseModelMixin):
    """订单商品"""
    order = models.ForeignKey(HappyShopOrderInfo, on_delete = models.PROTECT, verbose_name="订单")
    sku = models.ForeignKey(HappyShopSKU, on_delete = models.PROTECT, blank=True, null=True, verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField('单价', max_digits=18, decimal_places=2)
    is_commented = models.BooleanField(default=False, verbose_name="是否已评价")

    class Meta:
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name
    
    def __str__(self) -> str:
        return self.sku.spu.title


class HappyShopAddress(BaseModelMixin):
    """收货地址
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    name = models.CharField("签收人", max_length=50)
    phone = models.CharField("手机号", max_length=11)
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    province = models.CharField(max_length=150, verbose_name="省")
    city = models.CharField(max_length=150, verbose_name="市")
    county = models.CharField(max_length=150, verbose_name="区/县")
    address = models.CharField(max_length=150, verbose_name="详细地址")
    is_default = models.BooleanField(default=False, verbose_name="设为默认")
    
    class Meta:
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name
        constraints = [
            # 默认地址唯一约束
            models.UniqueConstraint(fields=('id', 'is_default'), name="unique_happy_addr")
        ]

    def __str__(self):
        return f'{self.name} {self.address}'
    
    @classmethod
    def get_default(cls, user, is_default=True):
        """[获取默认收货地址]

        Args:
            user (request.user): 当前登录用户对象

        Returns:
            [Queryset]: 所属用户的默认收货地址的queryset数据
        """
        return cls.objects.filter(owner=user, is_default=is_default)


class HappyShopingCart(BaseModelMixin):
    # 购物车数据模型
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    sku = models.ForeignKey(HappyShopSKU, on_delete=models.CASCADE, verbose_name="商品sku")
    num = models.PositiveIntegerField(default=1, verbose_name="数量")
    
    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = verbose_name
        constraints = [
            models.UniqueConstraint(fields=['owner', 'sku'], name='unique_owner_sku_happy')
        ]
        
    def __str__(self):
        return f'{self.owner}{self.sku}'
    
    @classmethod
    def get_cart_count(cls, user):
        # 当前用户的购物车数量
        return cls.objects.filter(owner=user).count()

happy_shop/api/views/base.py
from rest_framework import viewsets
from rest_framework import mixins
from happy_shop.models import HappyShopBanner
from happy_shop.api.serializers.base import HappyShopBannerSerializer


class HappyShopBannerViewsets(mixins.ListModelMixin, viewsets.GenericViewSet):
    """banner视图
    list:
        banner列表
    """
    serializer_class = HappyShopBannerSerializer

    def get_queryset(self):
        return HappyShopBanner.objects.filter(is_del=False)

happy_shop/api/views/goods.py
from rest_framework import viewsets
from rest_framework import mixins
# from django_filters import rest_framework as filters
from rest_framework import filters  # 筛选
from django_filters.rest_framework import DjangoFilterBackend  # 过滤
from rest_framework_extensions.cache.mixins import CacheResponseMixin
from happy_shop.models import (
    HappyShopCategory, HappyShopBrand, HappyShopSPU, HappyShopSKU
)
from happy_shop.api.serializers.goods import (
    HappyShopeCategorySerializer, HappyShopBrandSerializer, HappyShopeCategoryDetailSerializer,
    HappyShopSPUSerializer, HappyShopSKUSerializer
)

from ..pagination import HappyShopSKUPagination
from ..filters import (
    HappyShopSKUFilter, HappyShopSPUFilter, HappyShopCategoryFilter
)
class HappyShopCategoryViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):

    """
    分类列表视图，返回所有的商品列表数据
    list:
        商品分类列表数据
    """
   
    # filter_backends = [MyFilterBackend]
    filterset_class = HappyShopCategoryFilter

    def get_serializer_class(self):
        """ 动态序列化 """
        if self.action == "list":
            return HappyShopeCategorySerializer
        elif self.action == "retrieve":
            return HappyShopeCategoryDetailSerializer
        return HappyShopeCategorySerializer
    
    def get_queryset(self):
        """ 根据不同的请求返回不同的数据 """
        cates_queryset = HappyShopCategory.objects.filter(is_del=False, parent__isnull=True)
        if self.action == "list":
            return cates_queryset
        elif self.action == "retrieve":
            return HappyShopCategory.objects.filter(is_del=False)
        return cates_queryset


class HappyShopBrandViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ HappyShopBrand 商品品牌接口

    list:
        @params mixins.ListModelMixin
        返回商品品牌列表
    retrieve:
        @params mixins.RetrieveModelMixin
        返回商品品牌详情
    """
    queryset = HappyShopBrand.objects.filter(is_del=False)
    serializer_class = HappyShopBrandSerializer


class HappyShopSPUViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ SPU  
    spu可以全局缓存，因为不影响库存
    """
    queryset = HappyShopSPU.objects.filter(is_del=False)
    serializer_class = HappyShopSPUSerializer
    filterset_class = HappyShopSPUFilter
    filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
    search_fields = ("title", "sub_title")
    ordering_fields = ('skus__sell_price',)


class HappyShopSKUViewsets(mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ SKU  
    sku则不能全局缓存，因为库存会实时变动，需要更精细化控制
    """
    queryset = HappyShopSKU.objects.filter(is_del=False)
    serializer_class = HappyShopSKUSerializer
    filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
    filterset_class = HappyShopSKUFilter
    pagination_class = HappyShopSKUPagination
    search_fields = ("spu__title", "spu__sub_title")
    ordering_fields = ('sell_price', 'sales', 'sort')

happy_shop/views/goods.py
from django.views.generic import TemplateView, DetailView
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
# from django.conf import settings
from happy_shop.conf import happy_shop_settings
from happy_shop.models import (
    HappyShopCategory, HappyShopSPU, HappyShopBrand, HappyShopSKU,
    HappyShopRate, HappyShopOrderSKU)
from happy_shop.filters import HappyShopSPUFilter, HappyShopSKUFilter
from happy_shop.models.order import HappyShopOrderInfo

from .views import BaseView


class IndexView(BaseView, TemplateView):
    """首页视图"""
    template_name = 'happy_shop/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cate_skus_dict'] = self.get_cate_skus()
        return context
    
    def get_cate_skus(self):
        parent_cates = HappyShopCategory.objects.filter(parent__isnull=True, is_nav=True)
        cate_skus_dict = {}
        for cate in parent_cates:
            sub_cates = cate.sub_cates.filter(is_del=False, is_nav=True).values_list('id', flat=True)
            skus = HappyShopSKU.objects.filter(spu__category__id__in=list(sub_cates)).distinct()
            print(skus)
            cate_skus_dict[cate.name] = skus[:happy_shop_settings.FLOOR_NUM]
        return cate_skus_dict


class HappyShopCategoryView(BaseView, SingleObjectMixin, ListView):
    """ 商品列表页即商品分类详情页
    最终返回的是当前分类下的sku的queryset数据
    """
    template_name = "happy_shop/goods.html"
    paginate_by = happy_shop_settings.PAGE_SIZE
    
    def get(self, request, *args, **kwargs):
        # 当前分类数据
        self.object = self.get_object(queryset=HappyShopCategory.objects.filter(is_del=False))
        return super().get(request, *args, **kwargs)
    
    def get_queryset(self):
        qs_filter = self.get_filter_queryset()
        queryset = qs_filter.qs
        return queryset
    
    def get_filter_queryset(self):
        """ 筛选过的数据 """
        spus = self.object.spu_cates.filter(is_del=False)
        skus_id = []
        for spu in spus:
            skus_id += list(spu.skus.values_list('id', flat=True))
        queryset = HappyShopSKU.objects.filter(id__in=skus_id, is_del=False)
        return HappyShopSKUFilter(self.request.GET, queryset)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['goods'] = self.get_filter_queryset()
        context['brands'] = self.get_brands()
        context['category'] = self.object

        if self.request.GET.get('brand'):
            context['brand_id'] = int(self.request.GET.get('brand'))
        else:
            context['brand_id'] = None
        return context
    
    def get_brands(self):
        """ 当前分类的品牌数据 """
        return self.object.brand_cates.filter(is_del=False)


class HappyShopSPUDetailView(BaseView, DetailView):
    """ 商品详情页
    """
    queryset = HappyShopSPU.objects.filter(is_del=False)
    template_name = 'happy_shop/detail.html'
    context_object_name = 'spu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['goods_news'] = self.get_goods()[:happy_shop_settings.NEW_NUM]
        context['comments'] = self.get_rates_all()
        context['rate'] = self.get_rate() 
        context['score'] = self.get_score()
        return context

    def get_goods(self):
        # 新品推荐
        cates = self.get_object().category.filter(is_del=False)
        skus_id = []
        for cate in cates:
            spus = cate.spu_cates.filter(is_del=False, is_new=True)
            for spu in spus:
                skus_id += list(spu.skus.values_list('id', flat=True))
        queryset = HappyShopSKU.objects.filter(id__in=list(set(skus_id)), is_del=False)
        if not queryset:
            queryset = self.get_object().skus.filter(is_del=False)
        return queryset
    
    def get_rates_all(self):
        """当前商品下的所有评价
        """
        # 当前spu下的所有sku
        skus_ids = self.get_object().skus.values_list('id', flat=True)
        # 拥有评论的sku_ids
        object_ids = HappyShopRate.objects.values_list('object_id', flat=True)
        # 当前商品下拥有的评论
        rates_list = []
        for object_id in object_ids:
            if HappyShopOrderSKU.objects.get(id=object_id).sku.id in skus_ids:
                rates_list.append(HappyShopRate.objects.get(object_id=object_id))  
        return rates_list
    
    def get_rate_gt_2(self):
        # 评分大于2的评价列表
        rates = []
        for rate in self.get_rates_all():
            if rate.rate >2:
                rates.append(rate)
        return rates
    
    def get_rate(self):
        """当前商品的评分
        计算方式为：求平均分
        如果还未有评价，则默认评分为4.6分
        """
        try:
            rate = sum([rate.rate for rate in self.get_rates_all()]) / len(self.get_rates_all())
        except ZeroDivisionError:
            rate = 4.6
        return rate
    
    def get_score(self):
        """评价满意度
        算法：评分大于2的数量在总评价数中的占比
        无评论默认为98%
        """
        try:
            score = f'{len(self.get_rate_gt_2()) / len(self.get_rates_all()) * 100}%'
        except ZeroDivisionError:
            score = '98%'
        return score

happy_shop/templates/happy_shop/categorys.html
{% extends 'happy_shop/base.html' %}
{% block title %}全部分类{% endblock %}

{% block breadcrumb_content %}
<b-breadcrumb align="is-left">
    <b-breadcrumb-item tag='a' href="{% url 'happy_shop:index' %}" >首页</b-breadcrumb-item>
    <!-- <b-breadcrumb-item tag='a' href="{% url 'happy_shop:user_profile' %}">个人中心</b-breadcrumb-item> -->
    <b-breadcrumb-item tag='a' active>全部分类</b-breadcrumb-item>
</b-breadcrumb>
{% endblock %}

{% block banner %}{% endblock %}
{% block main %}
<section class="section" id="allCategory">
    <div class="container">
        <template>
            {% for cate in navs %}
            <section>
                <b-collapse class="card" animation="slide" aria-id="contentIdForA11y3">
                    <template #trigger="props">
                        <div class="card-header" role="button" aria-controls="contentIdForA11y3">
                            <p class="card-header-title">
                                {{ cate.name }}
                            </p>
                            <a class="card-header-icon">
                                <b-icon :icon="props.open ? 'menu-down' : 'menu-up'">
                                </b-icon>
                            </a>
                        </div>
                    </template>
                    <div class="card-content">
                        <div class="content">
                            <div class="columns">
                                {% for sub_cate in cate.sub_cates %}
                                <div class="column is-2">
                                    <div class=" has-text-centered">
                                        <a class="box" href="{% url 'happy_shop:goods' sub_cate.id %}">
                                            <img src="{{ MEDIA_URL }}{{ sub_cate.icon }}" width="96px" height="96px"
                                                alt="{{ sub_cate.name }}">
                                            <p class=" has-text-primary"> {{ sub_cate.name }}</p>
                                        </a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </b-collapse>
            </section>
            {% endfor %}
        </template>
    </div>
</section>
{% endblock %}


{% block vue %}
    <script>
        var allCategory = new Vue({
            el:'#allCategory',
            data:{}
        })
    </script>
{% endblock %}
    

happy_shop/templates/happy_shop/head_top.html
<template>
    <nav class="navbar container">
        <div class="navbar-brand">
            <!-- <a class="navbar-item">
                <b-icon size="is-small" pack="mdi" icon="star-plus-outline"></b-icon>
                <span>收藏本站</span> 
            </a> -->
            <span class="navbar-item">欢迎光临本店！</span>
        </div>

        <div class="navbar-menu">
            <div class="navbar-end">
                {% if request.user.is_authenticated %}
                    <b-dropdown
                        v-model="navigation"
                        position="is-bottom-left"
                        append-to-body
                        aria-role="menu">
                        <template #trigger>
                            <a
                                class="navbar-item"
                                role="button">
                                <span>{{ request.user.username }}</span>
                                <b-icon icon="menu-down"></b-icon>
                            </a>
                        </template>
                        <b-dropdown-item custom aria-role="menuitem">
                            欢迎来到 <b>DJMall商城！</b>
                        </b-dropdown-item>
                        <hr class="dropdown-divider">
                        <b-dropdown-item has-link aria-role="menuitem">
                            <a href="{% url 'happy_shop:user_orders' %}" target="_blank">
                                <b-icon icon="toy-brick-plus-outline" size="is-small"></b-icon>
                                我的订单
                            </a>
                        </b-dropdown-item>
                        <b-dropdown-item  @click="logout">
                            <b-icon icon="logout" size="is-small"></b-icon>
                            退出
                        </b-dropdown-item>
                    </b-dropdown>
                {% else %}
                <a href="{% url 'happy_shop:register' %}" class="navbar-item pl-5 pr-5" 
                    style="border-right:solid 1px #eee;border-left:solid 1px #eee;">
                    <b-icon size="is-small" pack="mdi" icon="account-plus-outline"></b-icon>
                    <span>注册</span> 
                    
                </a> 
                <!-- <span class="navbar-item p-0">|</span> -->
                <a href="{% url 'happy_shop:login' %}" class="navbar-item pl-5 pr-5" style="border-right:solid 1px #eee;">
                    <b-icon size="is-small" pack="mdi" icon="login-variant"></b-icon>
                    <span>登录</span> 
                </a>
                {% endif %}
                <a href="{% url 'happy_shop:cart' %}" class="navbar-item has-background-light pl-4 pr-4">
                    <span class="icon is-small"><i class="mdi mdi-cart-minus"></i></span>
                    <span class="pl-2">购物车(<span v-if='cartNum'>{$ cartNum $}</span> <i v-else>0</i>)</span> 
                </a>
            </div>
        </div>    
    </nav>
</template>

happy_shop/templates/happy_shop/order_sku_detail.html
{% extends 'happy_shop/user_profile.html' %}
{% block extra_style %}{% endblock %}

{% block breadcrumb_content %}
<b-breadcrumb align="is-left">
    <b-breadcrumb-item tag='a' href="{% url 'happy_shop:index' %}" >首页</b-breadcrumb-item>
    <b-breadcrumb-item tag='a' href="{% url 'happy_shop:user_profile' %}">个人中心</b-breadcrumb-item>
    <b-breadcrumb-item tag='a' active>商品评价</b-breadcrumb-item>
</b-breadcrumb>
{% endblock %}

{% block menmber %}
<!-- <div class="box">
<article class="media">
    <figure class="media-left">
        <p class="image is-96x96">
            <img src="{{ MEDIA_URL }}{{ order_sku.sku.main_picture }}">
        </p>
    </figure>
    <div class="media-content">
        <h1 class="is-size">
            <a href="{% url 'happy_shop:goods_detail' order_sku.sku.spu.id %}" target="_blank">
                {{ order_sku.sku.spu.title }}
            </a>
        </h1>
        <p class="has-text-grey-light pt-1 pb-1">规格: {{ order_sku.sku.options.all|join:"," }} </p>
        <p class="has-text-grey-light">
            <span class="pr-4">数量: {{ order_sku.count }}</span>
            <span>单价: {{ order_sku.price }}</span>
        </p>

    </div>
    {% comment %} <div class="media-right">
        {% if not goods.is_commented and order.pay_status == 5 %}
        <a href="{% url 'happy_shop:user_orders_sku_detail' goods.id %}" class=" button is-small is-success is-outlined">去评价</a>
        
        {% elif goods.is_commented %}
        <button class="button is-small is-outlined">已评价</button>
        {% endif %}
    </div> {% endcomment %}
</article>
</div> -->
<div class="box1 is-shadowless">
    <h1>待评价商品：
        <a href="{% url 'happy_shop:goods_detail' order_sku.sku.spu.id %}" target="_blank">
        {{ order_sku.sku.spu.title }}
        </a>
    </h1>
    <div class=" dropdown-divider"></div>
    <div class="is-block">
        <b-field label="评价：">
            <b-input v-model="comment" maxlength="200" type="textarea" placeholder="期待您诚恳的评价！"></b-input>
        </b-field>
        <div style="position: relative; top:-20px">
            <div class="is-pulled-left">
                <span >评分：</span>
            </div>
            <div>
                <b-rate v-model="rate" spaced :max="maxs" :texts="texts" show-text :custom-text="custom"></b-rate>
            </div>
            <div class="is-clearfix"></div>
        </div>
        {% comment %} 后端待处理 {% endcomment %}
        <b-button type="is-primary" expanded @click="addRate({{order_sku.id}})">发布评价</b-button>
    </div>
</div>
{% endblock %}

happy_shop/templates/happy_shop/orders_tag.html
{% load tpl_tags %}
{% for order in orders %}
<div class="box">
    <p class="pb-3">订单日期：{{ order.add_date }}</p>
    {% for goods in order.happyshopordersku_set.all %}
    <article class="media">
        <figure class="media-left">
            <p class="image is-96x96">
                <img src="{{ MEDIA_URL }}{{ goods.sku.main_picture }}">
            </p>
        </figure>
        <div class="media-content">
            <h1 class="is-size">
                <a href="{% url 'happy_shop:goods_detail' goods.sku.spu.id %}" target="_blank">
                    {{ goods.sku.spu.title }}
                </a>
            </h1>
            <p class="has-text-grey-light pt-1 pb-1">规格: {{ goods.sku.options.all|join:"," }} </p>
            <p class="has-text-grey-light">
                <span class="pr-4">数量: {{ goods.count }}</span>
                <span>单价: {{ goods.price }}</span>
            </p>

        </div>
        <div class="media-right">
            {% if not goods.is_commented and order.pay_status == 4 %}
            {% comment %} <a @click="isCommentModalActive = true" class=" button is-small is-success is-outlined">去评价</a> {% endcomment %}
            <a href="{% url 'happy_shop:user_orders_sku_detail' goods.id %}" class=" button is-small is-success is-outlined">去评价</a>
            
            {% elif goods.is_commented %}
            <button class="button is-small is-outlined">已评价</button>
            {% endif %}
        </div>
    </article>
    {% comment %} {% include 'happy_shop/comment_modal.html' %} {% endcomment %}
    {% endfor %}
    <div class="is-block has-background-light p-3">
        <div class="is-pulled-left">
            <button class="button is-narrow is-small is-warning is-light has-text-weight-bold">实付：¥{{ order.total_amount }}</button> 
        </div>
        <div class="is-pulled-right">
            {% if order.pay_status == 1 %}
            <a class="button is-small is-info is-outlined" href="{% alipay_url order.order_sn %}" target="_blank">
                <span class="pr-3 pt-1 pl-2">
                    <svg t="1632459990510" class="icon" viewBox="0 0 1024 1024" version="1.1"
                        xmlns="http://www.w3.org/2000/svg" p-id="2407" width="32" height="32">
                        <path
                            d="M1023.795 853.64v6.348a163.807 163.807 0 0 1-163.807 163.807h-696.18A163.807 163.807 0 0 1 0 859.988v-696.18A163.807 163.807 0 0 1 163.807 0h696.181a163.807 163.807 0 0 1 163.807 163.807V853.64z"
                            fill="#009FE9" p-id="2408"></path>
                        <path
                            d="M844.836 648.267c-40.952-14.333-95.623-34.809-156.846-57.128a949.058 949.058 0 0 0 90.094-222.573H573.325V307.14h245.711v-43.41l-245.71 2.458V143.33H472.173c-18.223 0-21.704 20.476-21.704 20.476v102.38H204.759v40.952h245.71v61.427H245.712v40.952h409.518a805.522 805.522 0 0 1-64.909 148.246c-128.384-42.795-266.186-77.604-354.233-55.08a213.564 213.564 0 0 0-112.003 63.27c-95.418 116.917-26.21 294.034 175.274 294.034 119.989 0 236.087-67.366 325.771-177.73 134.322 65.932 398.666 176.297 398.666 176.297V701.3s-32.352-4.095-178.96-53.033z m-563.702 144.97c-158.893 0-204.759-124.699-126.336-194.112a191.86 191.86 0 0 1 90.913-46.276c93.575-10.238 189.811 35.629 293.624 86.614-74.941 94.598-166.674 153.774-258.2 153.774z"
                            fill="#FFFFFF" p-id="2409"></path>
                    </svg>
                </span>
                支付宝支付
            </a>
            {% elif order.pay_status == 3 %}
            <a @click="confirmOrders({{order.id}})" class="button is-small is-primary">确认收货</a>
            {% comment %} {% elif order.pay_status == 5 %} {% endcomment %}
            <!-- <span class=" has-text-danger-dark">{{ order.get_pay_status_display }}</span> -->
            {% endif %}
            <button class="button is-small">{{ order.get_pay_status_display }}</button>
            <a href="{% url 'happy_shop:user_orders_detail' order.id %}" class=" button is-small is-primary is-outlined">查看详情</a>
        </div>
        <div class="is-clearfix"></div>
    </div>
</div>
{% endfor %}

happy_shop/templates/happy_shop/register.html
{% extends 'happy_shop/login.html' %}

{% block title %}注册-{{ title }}{% endblock %}

{% block form_title %}注册{% endblock %}

{% block form %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class=" mb-5">
            <b-field label="{{ field.label }}"
                :label-position="labelPosition">
                {{ field }}
                <template #message>
                    {% if field.errors %}
                    <div class=" has-text-danger">{{ field.errors }}</div>
                    {% else %}
                    {{ field.help_text }}
                    {% endif %}
                </template>
            </b-field>
        </div>
        {% endfor %}
        <input type="hidden" name="next" value="{{ next }}">
        <input type="submit" class=" button is-fullwidth is-primary" value="注册">
    </form>
{% endblock %}
    